---
title: \vspace{.5in}"__homework_7_kanutala_santosh__"
author: "__Santosh Kanutala__"
date: "7/22/2018"
output:
  pdf_document:
    toc: yes
    toc_depth: 3
    highlight: tango
  html_document:
    highlight: tango
    number_sections: no
    theme: readable
    toc: yes
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newpage
## <u>Github location</u>
My homework assignments can be found at   https://github.com/santumagic/compscix-415-2assignments.git

## <u>Exercise 1</u>
```{r load_packages, message=FALSE, warning=FALSE}
# Load the required packages
library(tidyverse)
library(mdsr)
```
```{r Ex_1, message=FALSE, warning=FALSE}
# Load the train.csv file
train <- read.csv ("/Users/skanutal/Documents/Santosh/Learning/Berkeley/3. Intro to DS/Assignments/train.csv", sep = "," )
# glimpse the data from the final csv file
glimpse(train)
```

**Answer:**
There are 81 variables, and 1460 observations

## <u>Exercise 2</u>
```{r Ex_2, message=FALSE, warning=FALSE, fig.align='center'}

# Install the required pacages and load them
# install.packages("broom") # commented to not to run each time
library(broom)

# Visualize the distribution of SalePrice
# Plot the histogram
# Visualize the covariation between SalePrice and Neighborhood
# Visualize the covariation between SalePrice and OverallQual

```


## <u>Exercise 3</u>
```{r Ex_2_Q1, message=FALSE, warning=FALSE, fig.align='center'}
# take a look at the coefficient
simple <- lm(SalePrice ~ 1, data = train)
tidy(simple)
```

**Answer:**
The coefficient is: 180921.2

```{r Ex_2_Q2, message=FALSE, warning=FALSE, fig.align='center'}
# compare the coefficient to the average value of SalePrice
avg_val <- mean(train$SalePrice)
avg_val
```

**Answer:**
The average value of the sale price from the train data set is equal to the coefficient and is equal to 180921.2

```{r Ex_2_Q3, message=FALSE, warning=FALSE, fig.align='center'}
# take a look at the R-squared
glance(simple)
```


## <u>Exercise 4</u>