---
title: "COMPSCIX 415.2 Homework 5/Midterm"
author: "Santosh Kanutala"
date: "7/5/2018"
output:
  html_document: 
    #df_print: paged
    toc: true # table of content true
    toc_depth: 3  # upto three depths of headings (specified by #, ## and ###)
    number_sections: true  ## if you want number sections at each table header
    theme: united  # many options for theme, this one is my favorite.
    highlight: tango  # specifies the syntax highlighting style
  #pdf_document: default
  #self_contained: true
  #theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Github location
(https://github.com/santumagic/compscix-415-2assignments.git)

## RStudio and R Markdown
```{r load_packages, message=FALSE, warning=FALSE}
# Load the required packages
library(tidyverse)
library(mdsr)
library(nycflights13)
```

### Question: 1


## The tidyverse packages

### Question: 1

### Question: 2

## R Basics

### Question: 1

### Question: 2

### Question: 3

## Data import/export

### Question: 1

### Question: 2

## Visualization

### Question: 1

### Question: 2

### Question: 3

## Data munging and wrangling

### Question: 1

### Question: 2

### Question: 3

## EDA

### Question: 1

### Question: 2

### Question: 3

### Question: 4

### Question: 5

### Question: 6

## Git and Github








